export const UNITS_IMPERIAL = 'Imperial';
export const UNITS_METRIC = 'Metric';
export const LENGTH_CHOICE_RIDGELINE = 'Ridgeline length';
export const LENGTH_CHOICE_HAMMOCK = 'Hammock length';
export const HANG_ANGLE_CHOICES = [5, 15, 20, 30, 45];

export const DEFAULT_UNITS = UNITS_IMPERIAL;
export const DEFAULT_DISTANCE_BETWEEN_TREES = 15;
export const DEFAULT_LENGTH_CHOICE = LENGTH_CHOICE_RIDGELINE;
export const DEFAULT_LENGTH = 108;
export const DEFAULT_SIT_HEIGHT = 18;
export const DEFAULT_WEIGHT = 200;
export const DEFAULT_HANG_ANGLE = HANG_ANGLE_CHOICES[3];

export const ACTIONS = {
  CHANGE_UNITS: 'CHANGE_UNITS',
  SET_DISTANCE_BETWEEN_TREES: 'SET_DISTANCE_BETWEEN_TREES',
  SET_LENGTH_CHOICE: 'SET_LENGTH_CHOICE',
  SET_LENGTH: 'SET_LENGTH',
  SET_SIT_HEIGHT: 'SET_SIT_HEIGHT',
  SET_WEIGHT: 'SET_WEIGHT',
  SET_HANG_ANGLE: 'SET_HANG_ANGLE',
};
